# Environment file for cil-project

name: cil-project

channels:
  - conda-forge
  - anaconda
  - pytorch

dependencies:
  - python=3.10
  - numpy
  - pandas
  - pip
  - scikit-learn
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::cpuonly # comment out if commenting in lines below for CUDA
#  - nvidia::cudatoolkit=11.7
#  - pytorch::pytorch-cuda=11.7