# Environment file for cil-project

name: cil-project

channels:
  - conda-forge
  - anaconda
  - pytorch
  - nvidia

dependencies:
  - python>=3.10
  - numpy
  - pandas
  - pip:
      - myfm
  - tqdm
  - scikit-learn
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::cpuonly # comment out if commenting in lines below for CUDA
#  - pytorch::pytorch-cuda=12.1
#  - nvidia::cuda-libraries-dev=12.1.*
#  - nvidia::cuda-nvcc=12.1.*
#  - nvidia::cuda-nvtx=12.1.*
#  - nvidia::cuda-cupti=12.1.*
#  - nvidia::cuda-cudart-dev=12.1.*
#  - nvidia::cuda-profiler-api=12.1.*